# Generated by Django 2.1.2 on 2019-01-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIPTImportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=50, unique=True, verbose_name='样本编号')),
                ('name', models.CharField(max_length=10, verbose_name='孕妇姓名')),
                ('date_blood', models.DateField(verbose_name='采血时间')),
                ('age', models.CharField(max_length=10, verbose_name='孕妇年龄')),
                ('gestation_weeks', models.CharField(blank=True, max_length=20, null=True, verbose_name='孕周')),
                ('last_menstrual', models.DateField(blank=True, null=True, verbose_name='末次月经')),
                ('fetus_number', models.CharField(blank=True, choices=[('单胎', '单胎'), ('双胎', '双胎'), ('三胎', '三胎'), ('多胎', '多胎')], default='单胎', max_length=20, null=True, verbose_name='胎儿数量')),
                ('tube_baby', models.CharField(blank=True, choices=[('否', '否'), ('是', '是')], default='否', max_length=10, null=True, verbose_name='试管婴儿')),
                ('telephone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('hospital', models.CharField(blank=True, max_length=50, null=True, verbose_name='送检医院')),
                ('doctor', models.CharField(blank=True, max_length=20, null=True, verbose_name='送检医生')),
                ('province', models.CharField(blank=True, max_length=20, null=True, verbose_name='省区')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('report_area', models.CharField(choices=[('成都', '成都'), ('福州总医院', '福州总医院'), ('湘雅医院', '湘雅医院'), ('贵州医科大学附属医院', '贵州医科大学附属医院'), ('吉林省妇幼', '吉林省妇幼'), ('西南医院', '西南医院'), ('长治妇幼', '长治妇幼'), ('山东检验所', '山东检验所'), ('山东凡迪', '山东凡迪'), ('广东省妇幼', '广东省妇幼'), ('扬州市妇幼保健院', '扬州市妇幼保健院'), ('宜春妇幼保健医院', '宜春妇幼保健医院'), ('河北省医科大学第二医院', '河北省医科大学第二医院'), ('武汉市中心医院', '武汉市中心医院')], default='成都', max_length=50)),
                ('T13', models.CharField(max_length=10, verbose_name='13号染色体值')),
                ('T18', models.CharField(max_length=10, verbose_name='18号染色体值')),
                ('T21', models.CharField(max_length=10, verbose_name='21号染色体值')),
                ('result', models.CharField(choices=[('未见异常', '未见异常'), ('chr13三体高风险', 'chr13三体高风险'), ('chr13三体低风险', 'chr13三体低风险'), ('chr18三体高风险', 'chr18三体高风险'), ('chr18三体低风险', 'chr18三体低风险'), ('chr21三体低风险', 'chr21三体低风险'), ('chr21三体低风险', 'chr21三体低风险')], default='未见异常', max_length=30, verbose_name='检测结果')),
                ('date_report', models.DateField(verbose_name='报告时间')),
                ('state_report', models.IntegerField(blank=True, default=1, null=True, verbose_name='报告状态')),
                ('person_import', models.CharField(blank=True, max_length=10, null=True, verbose_name='导入人员')),
                ('date_import', models.DateTimeField(blank=True, null=True, verbose_name='导入时间')),
                ('DS21_result', models.CharField(blank=True, choices=[('null', 'null'), ('未做', '未做'), ('高危', '高危'), ('低危', '低危')], default='null', max_length=10, null=True, verbose_name='21号唐筛结果')),
                ('DS21_value', models.CharField(blank=True, max_length=10, null=True, verbose_name='21号唐筛值')),
                ('DS18_result', models.CharField(blank=True, choices=[('null', 'null'), ('未做', '未做'), ('高危', '高危'), ('低危', '低危')], default='null', max_length=10, null=True, verbose_name='18号唐筛结果')),
                ('DS18_value', models.CharField(blank=True, max_length=10, null=True, verbose_name='18号唐筛值')),
                ('DSother_result', models.CharField(blank=True, choices=[('null', 'null'), ('未做', '未做'), ('高危', '高危'), ('低危', '低危')], default='null', max_length=10, null=True, verbose_name='其他唐筛结果')),
                ('preghistory', models.CharField(blank=True, max_length=50, null=True, verbose_name='妊娠史')),
                ('upload_excel', models.FileField(blank=True, null=True, upload_to='NIPT/%Y/%m', verbose_name='数据上传表')),
            ],
            options={
                'verbose_name': 'NIPT导入数据表',
                'verbose_name_plural': 'NIPT导入数据表',
            },
        ),
    ]
