# Generated by Django 2.1.2 on 2019-01-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NIPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niptimportdata',
            name='date_report',
            field=models.DateField(default='', verbose_name='报告时间'),
        ),
    ]
